language: elixir
elixir:
  - 1.6.5
  - 1.7.3
otp_release:
  - 20.0
  - 21.0
script:
  - mix test --no-start --trace --cover
  - MIX_ENV=test mix credo --strict
  - cd test/integration
  - mix deps.get
  - mix test --no-start --trace --include integration
services:
  - redis-server
sudo: false
